// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.focustech.portfolio.domain;

import com.focustech.portfolio.domain.PortfolioDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PortfolioDataOnDemand_Roo_Configurable {
    
    declare @type: PortfolioDataOnDemand: @Configurable;
    
}
