// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.focustech.portfolio.domain;

import com.focustech.portfolio.domain.PortfolioDataOnDemand;
import com.focustech.portfolio.domain.PortfolioIntegrationTest;
import com.focustech.portfolio.service.PortfolioService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PortfolioIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PortfolioIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PortfolioIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PortfolioIntegrationTest: @Transactional;
    
    @Autowired
    private PortfolioDataOnDemand PortfolioIntegrationTest.dod;
    
    @Autowired
    PortfolioService PortfolioIntegrationTest.portfolioService;
    
    @Test
    public void PortfolioIntegrationTest.testCountAllPortfolios() {
        Assert.assertNotNull("Data on demand for 'Portfolio' failed to initialize correctly", dod.getRandomPortfolio());
        long count = portfolioService.countAllPortfolios();
        Assert.assertTrue("Counter for 'Portfolio' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PortfolioIntegrationTest.testFindPortfolio() {
        Portfolio obj = dod.getRandomPortfolio();
        Assert.assertNotNull("Data on demand for 'Portfolio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Portfolio' failed to provide an identifier", id);
        obj = portfolioService.findPortfolio(id);
        Assert.assertNotNull("Find method for 'Portfolio' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Portfolio' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PortfolioIntegrationTest.testFindAllPortfolios() {
        Assert.assertNotNull("Data on demand for 'Portfolio' failed to initialize correctly", dod.getRandomPortfolio());
        long count = portfolioService.countAllPortfolios();
        Assert.assertTrue("Too expensive to perform a find all test for 'Portfolio', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Portfolio> result = portfolioService.findAllPortfolios();
        Assert.assertNotNull("Find all method for 'Portfolio' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Portfolio' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PortfolioIntegrationTest.testFindPortfolioEntries() {
        Assert.assertNotNull("Data on demand for 'Portfolio' failed to initialize correctly", dod.getRandomPortfolio());
        long count = portfolioService.countAllPortfolios();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Portfolio> result = portfolioService.findPortfolioEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Portfolio' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Portfolio' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PortfolioIntegrationTest.testFlush() {
        Portfolio obj = dod.getRandomPortfolio();
        Assert.assertNotNull("Data on demand for 'Portfolio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Portfolio' failed to provide an identifier", id);
        obj = portfolioService.findPortfolio(id);
        Assert.assertNotNull("Find method for 'Portfolio' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPortfolio(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Portfolio' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PortfolioIntegrationTest.testUpdatePortfolioUpdate() {
        Portfolio obj = dod.getRandomPortfolio();
        Assert.assertNotNull("Data on demand for 'Portfolio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Portfolio' failed to provide an identifier", id);
        obj = portfolioService.findPortfolio(id);
        boolean modified =  dod.modifyPortfolio(obj);
        Integer currentVersion = obj.getVersion();
        Portfolio merged = portfolioService.updatePortfolio(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Portfolio' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PortfolioIntegrationTest.testSavePortfolio() {
        Assert.assertNotNull("Data on demand for 'Portfolio' failed to initialize correctly", dod.getRandomPortfolio());
        Portfolio obj = dod.getNewTransientPortfolio(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Portfolio' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Portfolio' identifier to be null", obj.getId());
        portfolioService.savePortfolio(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'Portfolio' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PortfolioIntegrationTest.testDeletePortfolio() {
        Portfolio obj = dod.getRandomPortfolio();
        Assert.assertNotNull("Data on demand for 'Portfolio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Portfolio' failed to provide an identifier", id);
        obj = portfolioService.findPortfolio(id);
        portfolioService.deletePortfolio(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Portfolio' with identifier '" + id + "'", portfolioService.findPortfolio(id));
    }
    
}
